config/routes.rb
Rails.application.routes.draw do
  resources :shops
  resources :users
  resources :posts
  root to: 'home#index'
  get "home/about" => "home#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    has_many :users
end

app/models/post.rb
class Post < ApplicationRecord
    attachment :product_image
    belongs_to :shop
    has_many :comments
end

app/models/shop.rb
class Shop < ApplicationRecord
    has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :comment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to posts_path
  end
  
  def update

  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:product, :price, :product_comment, :product_image)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops = Shop.all
  end

  def show
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def update
  end

  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def edit
  end

  def update
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<h1>アバウト</h1>

app/views/home/index.html.erb
<h1>トップページ</h1>

app/views/home/top.html.erb
<h1>トップページ</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BargainInformation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>投稿編集</h1>

<%= form_for(@post) do |f| %>
    <h4>商品画像</h4>
    <%= f.attachment_field :product_image %>
    <h4>商品</h4>
    <%= f.text_field :product %>
    <h4>値段</h4>
    <%= f.text_area :price %>
    <h4>ショップコメント</h4>
    <%= f.text_area :product_comment %>
    <br><%= f.submit '保存' %></br>

    <%= link_to "Show", post_path(@post) %>
    <%= link_to "Back", posts_path %>

<% end %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>

<% @posts.each do |post| %>
    <%= post.product_image %>
    <%= post.product %>
    <%= post.price %>
    <%= post.product_comment %>
    <%= link_to '詳しく見る', post_path(post) %>
    <%= link_to "削除", post_path(post.id), method: :delete %>
<% end %>

app/views/posts/new.html.erb
<h1>新規投稿</h1>

<%= form_for(@post) do |f| %>

  <%= f.attachment_field :product_image %>

  <h4>商品</h4>
  <%= f.text_field :product %>

  <h4>値段</h4>
  <%= f.text_field :price %>

  <h4>ショップコメント</h4>
  <%= f.text_area :product_comment %>

  <%= f.submit '投稿' %>

<% end %>

app/views/posts/show.html.erb
<h1>投稿詳細</h1>


    <%= @post.product_image %>
    <%= @post.product %>
    <%= @post.price %>
    <%= @post.product_comment %>
    <%= link_to "削除", post_path(@post.id), method: :delete %>

app/views/shops/edit.html.erb
<h1>店舗情報編集</h1>

<%= form_for(@shop) do |f| %>
    <h4>店舗名</h4>
    <%= f.text_field :shop_name %>
    <h4>郵便番号</h4>
    <%= f.text_field :shop_postal_code %>
    <h4>店舗住所</h4>
    <%= f.text_area :shop_address %>
    <h4>メールアドレス</h4>
    <%= f.text_field :shop_email %>
    <br><%= f.submit '保存' %></br>

    <%= link_to "Show", shop_path(@shop) %>
    <%= link_to "Back", shops_path %>

<% end %>

app/views/shops/index.html.erb
<h1>店舗一覧</h1>

<% @shops.each do |shop| %>
    <%= shop.shop_name %>
    <%= shop.shop_postal_code %>
    <%= shop.shop_address %>
    <%= shop.email %>

    <%= link_to '詳しく見る', shop_path(shop) %>
    <%= link_to "削除", shop_path(shop.id), method: :delete %>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>